CREATE TABLE mon.striim_mon_table_comparison (
    tblcompareid BIGINT PRIMARY KEY,
    batchdate TIMESTAMP,
    appName TEXT,
    sourceName TEXT,
    targetName TEXT,
    srcNumOfDeletes BIGINT,
    tgtNumOfDeletes BIGINT,
    diffNumOfDeletes BIGINT,
    srcNumOfDdls BIGINT,
    tgtNumOfDdls BIGINT,
    diffNumOfDdls BIGINT,
    srcNumOfPkupdates BIGINT,
    tgtNumOfPkupdates BIGINT,
    diffNumOfPkupdates BIGINT,
    srcNumOfUpdates BIGINT,
    tgtNumOfUpdates BIGINT,
    diffNumOfUpdates BIGINT,
    srcNumOfInserts BIGINT,
    tgtNumOfInserts BIGINT,
    diffNumOfInserts BIGINT,
    sourceComponentName TEXT,
    targetComponentName TEXT
);
