CREATE TABLE mon.striim_mon_table_comparison_sli (
    tblcomparehistoryid BIGINT PRIMARY KEY,
    batchdate TIMESTAMP,
    timesincelastbatch BIGINT,
    appName TEXT,
    sourceName TEXT,
    targetName TEXT,
    srcNumOfDeletes_sli BIGINT,
    tgtNumOfDeletes_sli BIGINT,
    diffNumOfDeletes_sli BIGINT,
    srcNumOfDdls_sli BIGINT,
    tgtNumOfDdls_sli BIGINT,
    diffNumOfDdls_sli BIGINT,
    srcNumOfPkupdates_sli BIGINT,
    tgtNumOfPkupdates_sli BIGINT,
    diffNumOfPkupdates_sli BIGINT,
    srcNumOfUpdates_sli BIGINT,
    tgtNumOfUpdates_sli BIGINT,
    diffNumOfUpdates_sli BIGINT,
    srcNumOfInserts_sli BIGINT,
    tgtNumOfInserts_sli BIGINT,
    diffNumOfInserts_sli BIGINT,
    sourceComponentName TEXT,
    targetComponentName TEXT
);
